name: CI
on: [pull_request, push]
jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "23.0.4"
          elixir-version: "1.10.4"
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
