name: CI
on: [pull_request, push]
jobs:
  test:
    name: test
    strategy:
      matrix:
        elixir: ['1.13.4', '1.12.3', '1.11.4']
        otp: ['24.3', '23.3.4.14', '22.3.4.26']
        include:
          - elixir: '1.13.4'
            otp: '25.0'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix format --check-formatted
        if: ${{ matrix.elixir == '1.13.4' && matrix.otp == '25.0' }}
      - run: mix test
